### ISSUE TITLE
Alternative plotting library

### ISSUE THREAD

**Issue by xaratustrah** [xaratustrah/iq_suite#10]
Find an alternative plotting library with faster response.

**Comment by carlkl** [comment]
use imshow instead of pcolormesh :smirk:

**Comment by xaratustrah** [comment]
hmm.. ok one can deal with the reverse axis as shown in [this post](http://stackoverflow.com/a/21169703). But now sure about speed, and also the zooming feature. But surely worth trying. We'll have a look at it.

:-)
