### ISSUE TITLE
patched spectrum wheel for windows available

### ISSUE THREAD

**Issue by carlkl** [xaratustrah/iq_suite#14]
as the _freeze_ patch for windows https://github.com/cokelaer/spectrum/pull/12 is not yet merged I made windows spectrum wheels available at: https://anaconda.org/carlkl/spectrum

**Comment by xaratustrah** [comment]
done thanks. New gist can be found [here](https://gist.github.com/xaratustrah/4efc5001f1bbcce47e02e2343ba29b87)
