### ISSUE TITLE
Detailed installation instruction including requirements.txt

### ISSUE THREAD

**Issue by johngull** [xaratustrah/iq_suite#17]
I have a problem installing this library.
I can't find where to get multitaper module.

It will be very helpful if you will describe all required modules.

**Comment by xaratustrah** [comment]
oh I think I may have forgotten to update the documentation. The multitaper is it is a stand alone repo under my account. you can just use it here:

[https://github.com/xaratustrah/multitaper](https://github.com/xaratustrah/multitaper)

meanwhile I will try to update the docs.
cheers!
