### ISSUE TITLE
quick_introduction_iqtools.ipynb contains outdated functions

### ISSUE THREAD

**Issue by gwgwhc** [xaratustrah/iq_suite#25]
iqtools/doc/quick_introduction_iqtools.ipynb contains many outdated functions such as:
>`plot_spectrogram_dbm()`

 _replaced with `plot_spectrogram()`_
>`plot_dbm_per_hz()`

 _replaced with `plot_spectrum()`_
>`get_time_average_vs_frequency()`

_replaced with `get_fft()`_

This could be confusing for new users, especially since it is the most comprehensive example file included.

**Comment by xaratustrah** [comment]
Solved in commit v3.3.3.
