### ISSUE TITLE
Date times

### ISSUE THREAD

**Issue by DFreireF** [xaratustrah/iq_suite#31]
In the tiqdata.py, the self.date_time is not the time in which the data was recorded, specify which time is it. Although, it may be used for computing the time difference between files. 
In the tdmsdata.py, self.date_time, it is the 'ctime' which is completely useless, not even for computing the delta t between files. Use at least the 'mtime' which may be used for computing the deltas.

**Comment by xaratustrah** [comment]
@DFreireF solved at version #32
