### ISSUE TITLE
Add option to change delimiter in csvdata.py

### ISSUE THREAD

**Issue by gwgwhc** [xaratustrah/iq_suite#40]
The CSVData class uses the pipe character `|` as the delimiter by default with no option to change it.

Since it is a CSV, it makes sense that the default delimiter is in fact a comma. The option to add a user-specified delimiter can easily be added.

**Comment by xaratustrah** [comment]
Feature added in https://github.com/xaratustrah/iqtools/commit/326b177f9557380e6fb9338308f0e1912ccd07ea
